apiVersion: v1
kind: Secret
metadata:
  name: rf-auth-secret
  namespace: develop
type: Opaque
data:
  # echo -n "users_db" | base64 -> dXNlcnNfZGI=
  postgres-password: cmYtT3duZXIyNQ==
  postgres-user: cmlnaHRzZmxvdw==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rf-auth-svc
data:
  hostname: auth-svc
  profiles: local
  users_db: pg-users-db-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rf-auth-svc
  labels:
    app: rf-auth-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rf-auth-svc
  template:
    metadata:
      name: rf-auth-svc
      labels:
        app: rf-auth-svc
    spec:
      #      hostAliases:
      #        - ip: "192.168.1.22"
      #          hostnames:
      #            - "gitlab.micxem"
      containers:
        - name: rf-auth-svc
          image: gitlab.micxem:5050/rights-flow/rf-auth-svc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              protocol: TCP
          args: [ "--spring.profiles.active=$(RF_AUTH_SVC_PROFILES)"]
          env:
            - name: RF_AUTH_SVC_PROFILES
              valueFrom:
                configMapKeyRef:
                  name: rf-auth-svc
                  key: profiles
            - name: RF_EUREKA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rf-eureka-svc
                  key: serviceURL
            - name: RF_PG_USERS_DB_SVC
              valueFrom:
                configMapKeyRef:
                  name: rf-auth-svc
                  key: users_db
            - name: RF_AUTH_SVC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: rf-auth-svc
                  key: hostname
            - name: RF_CONFIG_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: rf-config-svc
                  key: serviceURL
            - name: PG_DB_USER
              valueFrom:
                secretKeyRef:
                  name: rf-auth-secret
                  key: postgres-user
            - name: PG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rf-auth-secret
                  key: postgres-password
          readinessProbe:
            httpGet:
              path: /auth/actuator/health/liveness
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /auth/actuator/health/liveness
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 15
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "384Mi"
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: rf-auth-svc
spec:
  selector:
    app: rf-auth-svc
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: 9000